### PR TITLE
Add back support for --url_prefix

### PR DESCRIPTION
**Pull request by theY4Kman**
This PR adds back the `--url_prefix` option. It modifies the routes to include the URL prefix, so a proper nginx config would look simply like:

```nginx
server {
    # ...
    location /flower/ {
        # no "rewrite /flower/(.*) /$1 break;" line
        proxy_pass http://localhost:5555;
    }
}
```

And run flower with:

```bash
flower --url_prefix=/flower/
```

### CODE REVIEW

**Comment by ranman** [comment]
I'd love to see this or #508 merged

**Comment by theY4Kman** [comment]
It doesn't seem like this will be merged. You might be okay with packaging up a version of Flower containing the code in this PR. I would recommend using this PR, because it not only changes the URL handlers, but also accounts for URLs in the JavaScript, so real-time components like the monitoring graphs will work.

**Comment by mher** [comment]
I reimplemented the support of --url-prefix option. Please try the master version.

**Comment by mher** [comment]
@theY4Kman thanks for the pull request! It is better to use `reverse_url`.

**Comment by theY4Kman** [comment]
I'm glad to hear it! I'll take a look at it later; I'd love to learn a
better way. My proposition felt a bit hackish.

**Comment by emaniacs** [comment]
I use flower with --url_prefix=flower and proxy with nginx so the flower url is http://mydomain/flower/,
but dashboard never updated(Websocket) because of condition in file https://github.com/mher/flower/blob/master/flower/static/js/flower.js#L560

`560: if ($.inArray($(location).attr('pathname'), ['/', '/dashboard']) !== -1) {`

I think you need expose url_prefix value in template.

**Pull request closed without merging**
