### PR TITLE
Enhancement: Added feature to manually retry failed tasks

### PR DESCRIPTION
**Pull request by tnir**
This PR is based on @jiffyjeff's work #158 with follow-up to be ready to be merged.

Enhancement: Added feature to manually retry failed tasks. Added "Requeue" button to task detail view; requeues the task with original args and kwargs using the Flower async-apply API. Supports an existing feature request (#17).

### CODE REVIEW

**Comment by tnir** [comment]
@asfaltboy @mher @ask This is a follow-up against #158. I'd like you to review this PR.

**Comment by tnir** [comment]
cc @embolalia @xrage @spudfkc

**Comment by tnir** [comment]
@jiffyjeff What do you think of this PR?

**Comment by SirEdvin** [comment]
Don't work, has problem with args parsing, because send tuple to json.

**Comment by jheld** [comment]
@tnir @SirEdvin Would you like any help fixing/testing this?

**Comment by tnir** [comment]
@jheld Yes if you can!

**Comment by viiicky** [comment]
@tnir any update on this, if this is going to be merged?

**Comment by clintonb** [comment]
What is preventing this from being merged?

**Comment by tnir** [comment]
@clintonb As far as I know, someone does not think this PR works well.

**Comment by jheld** [comment]
Last time I tried to use it, it didn't work. But I'm willing to try again.

**Comment by jheld** [comment]
One extra issue is that args or kwargs repr could be truncated. If the worker has an increased repr size, that can be a work around -- but out of control of this PR.

Also, is there a way to remember/use any child tasks?

Additionally, if the task result backend is enabled and the args/kwargs are there (newer version of celery, not yet released), then we could take from that if it is available.

**Comment by ryanprater** [comment]
+1

**Comment by tnir** [comment]
Should I do something to get merged?

**Comment by ryanprater** [comment]
@tnir yes please!

**Comment by jheld** [comment]
If you do, please have a warning in docs or something that this do not re-queue child tasks, and depending on the size of args/kwargs, the re-queue itself might not run (repr may be truncated). The latter can be dealt with as part of running celery, but I don't think the former can.

**Comment by jheld** [comment]
Another way to do this could be with use of the extended results feature on newer celery (4.3 I think), if all the settings are lined up. If the result backend has the tombstone and that extended setting is enabled, we should be able to get around the repr truncation issue at least.

**Comment by mikolaje** [comment]
good feature, why can't it be merged?

**Comment by jheld** [comment]
I think the idea is sound. But there are some caveats/documentation around it that I think would be required in this change should it be merged. If the truncation or extended results are not adjusted per the user, they may not be able to use the retry. That's effectively breakage from the user's perspective, unless there are prominently placed docs.

Due to how celery/events construct tasks and the flow in them, it makes this feature harder. Additionally, what happens if this task is part of a chain? We would like to ensure we can make it possible to call the rest of the chain should this task succeed on manual retry. That's my take, and I feel it's important to get it right if we can. If not, then yes, it could be left off for now.

**Comment by jheld** [comment]
@mher would you be able to add me as a collaborator/maintainer? I'd like to help merge this (once we agree on readiness/impact).

**Comment by mapineda** [comment]
Is there any update on this? @jheld

**Comment by jheld** [comment]
I feel we're still blocked by at least the truncation issue. If the result backend extended setting support is merged then that will technically allow this to work better (so long as the key is still in the backend, not expired).

So although this is a useful change, it's sitting in a boundary where a lot of folks are going to have breakage, so long as the other pieces aren't addressed.

**Comment by mher** [comment]
Closing this pull request because it will only work in limited cases

**Pull request closed without merging**
