### PR TITLE
Enhancement: Added feature to manually retry failed tasks. Added "Requeu...

### PR DESCRIPTION
**Pull request by jiffyjeff**
Enhancement: Added feature to manually retry failed tasks. Added "Requeue" button to task detail view; requeues the task with original args and kwargs using the Flower async-apply API. Supports an existing feature request (https://github.com/mher/flower/issues/17).

### CODE REVIEW

**Comment by asfaltboy** [comment]
@ask If someone were to continue implementing this; is this how you envision the flow?

0. Given CELERY_SEND_TASK_SENT_EVENT is enabled; together with a ALLOW_FAILED_TASK_RETRY toggle in flower.
1. Store/cache started task queue/exchange/routing-key as they arrive from `task-sent` event.
2. Store/cache original task args/kwargs (I may be wrong here, but they [appear to be included in `task-sent`](http://celery.readthedocs.org/en/latest/userguide/monitoring.html#task-sent)).
3. If task does not fail, remove the above stored data.
4. (optionally) allow cleaning up stored failed task metadata.
5. If user requests a retry, send `task.apply_async` (support `task.retry`?) to celery app.

While this satisfies our immediate requirement, it does feel to cover specific use cases.

However, now that I see that flower has the ability to schedule tasks, why not add an arbitrary task execution view? We could allow the task metadata (argument and routing) to be pre-filled from "saved instances" such as user defined or from previous tasks (i.e: filtered by status).

For the "retry" use case, I can envision users registering a task which handles task retries; the task, accepts task-ids as arguments, fetches task AsyncResult and retries task in the manner the user requires.

We obviously wouldn't be able to fit all use cases, but allowing arbitrary task execution and a dedicated "retry" task registered on user end, would allow us to forego the above steps (0-4) and still able to retry with the original data.

**Comment by embolalia** [comment]
I'd really like to pick this up and help get it merged. Echoing @asfaltboy, it sounds like what needs to be done is to cache the args, kwargs, exchange, and routing key. Then we send those on the resubmission. Is this accurate?

**Comment by tnir** [comment]
+1

@asfaltboy @mher @ask any update? what should I do to get it merged?

**Comment by xrage** [comment]
Will it be merged soon ??? Any Update...

**Comment by spudfkc** [comment]
@tnir It looks like the tests failed in python 3.2 and 3.3. It looks like that is what is holding this up.

**Comment by tnir** [comment]
@spudfkc Thanks for the follow-up. While the tests [failed for PR 158](https://travis-ci.org/mher/flower/builds/14897964), now flower doesn't use Python 3.2/3.3 for tests.

I just created [a new branch rebased on master](https://github.com/tnir/flower/tree/158-jiffyjeff-manual-retry) in [tnir/flower](https://github.com/tnir/flower) and [all tests passed](https://travis-ci.org/tnir/flower/builds/276697780). I would like to create a new PR if @jiffyjeff doesn't take their time to fix this PR.

**Comment by tnir** [comment]
I just created #737 to reduce lead time to be merged.

**Comment by ryanprater** [comment]
+1

**Comment by alexalv** [comment]
+1

**Comment by mher** [comment]
Closing this pull request. Task retry is definitely useful feature but unfortunately the current implementation will not work in many cases with truncated events and non-default queues.

**Pull request closed without merging**
