### PR TITLE
Added tasks table update via WebSockets

### PR DESCRIPTION
**Pull request by AndreLobato**
Implement DataTable updates via Websocket push #543 

Method may be incomplete still, but works fine, I have not yet run the test suite.

Suggestion for improvement, to add a switcher button to turn on/off the auto-updating since application could be processing too many tasks, making impossible to read the table.

### CODE REVIEW

**Comment by AndreLobato** [comment]
One problem I've identified is that if you have lots of tasking running and sending events, the page would take long to load since, the draw would be called many times before the page load. so would be nice if the websocket would be connected only after the table has been drawn for the first time.

**Comment by AndreLobato** [comment]
On this last update I have rationalised the calls for table.draw(), that's because, on the first implementation (calling table.draw for every new task event), at some point, the page would start to do excessive calls (GET) and jam the flower main process with too much calls, also is not a good approach since does little usage if the data sent by the WS pipe. To solve this problem I just added a time counter and set the a time threshold of 10s between each table.draw call. Also it will only try to call draw on task-received events, on all others events would just update the table row data if present, making a better usage of data flowing in the WS protocol.

**Comment by alcidesv** [comment]
Will this PR still allow Flower to run behind an HTTP/2 reverse proxy?

**Comment by mher** [comment]
WebSockets were removed from dashboard and I'm going to deprecate the API implementation. It is better to implement this using Datatables auto refresh.

**Pull request closed without merging**
