### PR TITLE
Add healthcheck endpoint

### PR DESCRIPTION
**Pull request by bmwant**
### Rationale

When running Flower with auth enabled using some orchestration service it's useful to have `healthcheck` endpoint which indicates status of the application without authN required.

### Examples
a)
AWS healthcheck for target group

Screen Shot 2020-07-25 at 7 16 20 PM
Screen Shot 2020-07-25 at 7 17 37 PM

b)
[docker-compose healthcheck](https://docs.docker.com/compose/compose-file/#healthcheck)
image
Screen Shot 2020-07-25 at 7 22 42 PM

### CODE REVIEW

**Comment by bmwant** [comment]
@mher let me know if that's something that can be added, so I can update unittests and docker-compose file [like here](https://github.com/tobybatch/kimai2/blob/main/docker-compose.yml#L32)

**Comment by mher** [comment]
`/metrics` endpoint can be used for the health check

**Comment by mher** [comment]
Duplicate of https://github.com/mher/flower/issues/945

**Comment by bmwant** [comment]
@mher the main difference is that `metrics` require `@web.authenticated`, so basically I need to send Auth header with credentials included for the healthcheck request which is not always possible. Is there a way to deal with that if I'm running flower with `celery flower -A app --basic_auth="user:pass"`?

**Comment by MarsssBlkm** [comment]
Having the same problem running Airflow with celery executor and flower. I have to set health check response as 401 as well for now.

**Comment by lggwettmann** [comment]
Same here, would be great if there would be an auth-free endpoint. Which alternatives are people using now?

**Comment by imressed** [comment]
@mher could you please share some more details regarding the health check and `/metrics` endpoint? 
As I can see metrics endpoint requires auth headers to be provided in order to get a response (and not 401 response) (i mean it has header `@web.authenticated`) 
Can it be a possible option to extend health-check functionality by adding an auth-free endpoint like proposed in this PR? 
I've already seen a couple of the same requests. Thanx for the update on this!

**Comment by mher** [comment]
Please add unit tests for the `/healthcheck` endpoint and I will merge the PR.

**Review by imressed — APPROVED** [review]

**Comment by lggwettmann** [comment]
Awesome guys and thanks for the fast work. Any plan on when you'll release this? :)

**Comment by bmwant** [comment]
@lggwettmann @mher added unittest, should be ready to go

**Comment by bmwant** [comment]
It is failing due to https://github.com/mozilla/MozDef/issues/1678. I can downgrade the lib but let's ask @mher about the proper action to do here

**Comment by mher** [comment]
@bmwant feel free to downgrade the version

**Pull request merged**
