### PR TITLE
Fixes #791: use parse_version instead of tuple comparisons

### LINKED ISSUE #791: invalid literal for int() with base 10: '0rc1'
Hi, 
After a recent update to celery main branch: https://github.com/celery/celery/commit/c7f2a8b6111692696f69c682dd2c57010bae5b6a

This causes the following error:
```
File "/usr/local/lib/python3.6/site-packages/flower/events.py", line 70, in __init__
    if self.persistent and tuple(map(int, celery.__version__.split('.'))) < (3, 0, 15):
ValueError: invalid literal for int() with base 10: '0rc1'
```
This is the problematic line:https://github.com/mher/flower/blob/master/flower/events.py#L70

Which causes flower to crash completely.
maybe this can help for better parsing the version number:
https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python/11887885#11887885

### PR DESCRIPTION
**Pull request by pachewise**
Not sure how to add a test for this.

### CODE REVIEW

**Comment by pachewise** [comment]
failures seem to be due to an existing issue (other PRs are failing in the same way, and tox run locally against master has the same issue)

**Comment by barqshasbite** [comment]
Maybe due to Tornado 5? Issue #784 indicates that it is a problem. The project uses tornado>=4.2.0, so switching to tornado>=4.2.0,<5.0.0 may be required for now.

**Comment by pachewise** [comment]
@barqshasbite thanks for pointing that out! Created PR #793 for fixing that issue

**Comment by pachewise** [comment]
@auvipy do you know how we can reach @mher or another contributor with write access?

**Comment by auvipy** [comment]
sorry no.

**Comment by mher** [comment]
Merged, thanks! @pachewise please add your name to the list of contributors

**Comment by david-caro** [comment]
Will there be a release for this fix?

**Pull request merged**
