### PR TITLE
Frontend upgrade

### PR DESCRIPTION
**Pull request by johanvergeer**
The goal of this PR was to upgrade jQuery (), DataTables () and Bootstrap ().

In order to accomplish this, and to make future upgrade easier, I chose to install the required dependencies with npm and to build the JavaScript and CSS modules with [Parcel](https://parceljs.org/).

The UI styles are kept very simple and only out-of-the-box Bootstrap classes are used. I would like to suggest to add custom classes to make things prettier again in another Pull Request.

# Browser support

Some legacy browsers cannot be supported by Flower anymore because of the upgrades to ES6 and Bootstrap 5.

- [ES6 syntax](https://caniuse.com/?search=es6)
- [JavaScript fetch API](https://caniuse.com/?search=fetch)
- [Bootstrap 5](https://getbootstrap.com/docs/5.0/getting-started/browsers-devices/)

# NPM commands

Building the JavaScript and CSS can be done with 2 different commands:

- `npm run watch`, which can be used during development. This command does the build, and rebuilds after every change to the JavaScript or CSS files
- `npm run build`, which builds and optimizes the JavaScript and CSS files
- `npm run prettier`, which runs the [Prettier](https://prettier.io/) formatter on all JavaScript and CSS files

### CODE REVIEW

**Comment by pabs3** [comment]
I suggest that when you migrate from one of the embedded code copies to a dependency, you remove the embedded code copies at the same time. For example you switched from moment.js to dayjs but didn't remove `moment.min.js` and `moment-timezone-with-data.min.js`. This will make it easier to see your progress in switching to npm installed dependencies.

**Comment by larsnaesbye** [comment]
LGTM 👍🏼

**Comment by johanvergeer** [comment]
@pabs3 @mher would you guys be able to review this PR?

**Comment by pabs3** [comment]
I don't know enough about JavaScript to be able to review it properly
and don't have merge rights, but I'll take a look soonish.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
@johanvergeer some thoughts in decreasing order of importance:

Firstly I don't know enough about JavaScript and the JS ecosystem to be able to review this PR properly and don't have merge rights.

In general what you have done looks fairly reasonable.

Please attach to a comment a zip file containing screenshots from before/after your PR, so that @mher and other reviewers can compare them. 

I would remove `package-lock.json`, so that people deploying Flower always get the latest version of dependencies that satisfies the version constraints in `package.json`. Otherwise they could miss out on a security update when `package-lock.json` gets out of date. Leave it up to them to generate a `package-lock.json` for their own installs if they want.

If it is possible to be compatible with earlier Bootstrap versions (4 at least), that would help in some situations since some people won't want to upgrade to version 5 just yet or haven't audited and approved it yet.

These files should be removed as it seems like they are all part of either Bootstrap or jQuery, so they should get used from those instead of embedded. The Apple icon files are even a big `B` for Bootstrap rather than an `F` for Flower or `C` for Celery.

```
flower/static/img/apple-touch-icon-*-precomposed.png
flower/static/img/glyphicons-halflings*.png
flower/static/src/css/images/ui-*.png
```

The screenshots in `original_pages/*.jpg` should be removed from the PR, as they are presumably for the version before your PR and so will be out of date when it gets merged?

Since `docs/screenshots/` is liable to get out of date due to this PR and future changes, it really should get removed and generated at build time (which is probably really hard to do), but for now, please update the screenshots that changed due to this PR. If anything else in the `docs/` dir needs to be updated due to changes added by this PR, please do that too.

Should `flower/static/src/css/flower.scss` also reference the Bootstrap SCSS using the `npm:` prefix instead of `node_modules` since someone could set `NODE_PATH` to a different location to the default?

`flower/static/favicon.ico` maybe needs recreating since the project was renamed from celeryadmin to flower and that no longer starts with a `c`. OTOH it does fit with `Celery Flower` which is the page title. Maybe `CF` for `Celery Flower` or just leave it as-is.

The git history for this is slightly confusing, looks like you duplicated commits on two different branches and then later merged them together? Maybe reorganise the commits to avoid that. I'd maybe squash all the commits into one diff and then reorganise it into a few logical commits.

The `docker-compose.yml` whitespace change can be dropped from the pull request.

**Comment by kshen3778** [comment]
@johanvergeer Any updates on this?

**Comment by u1735067** [comment]
Information that might be relevant to this PR, Flower 1.2 is flagged as vulnerable to sonatype-2020-0988 due to `datatables.net` (some informations can be found at https://issues.apache.org/jira/browse/YARN-11309), so while I have not checked the content of this PR, it might fix this.

**Comment by mmdanziger** [comment]
This PR should get flower out of security blacklist. Would mean a lot to us if this could get merged.

**Comment by pabs3** [comment]
@johanvergeer there was a major update (see #1280) in git master, so you might need to rebase your patches for this PR.

**Comment by johanvergeer** [comment]
@pabs3 @kshen3778 @mmdanziger  Given that there doesn't seem to be much willingness from the maintainers to merge this PR I decided to not continue working on it. If I could get a bit more cooperation and/or feedback from @mher I would be willing to proceed.

**Pull request closed without merging**
