### PR TITLE
Better detail in the task view

### PR DESCRIPTION
**Pull request by rodrigopmatias**
The viewer tasks, has been enhanced to display the key word arguments and arguments showing now indented way information.

### CODE REVIEW

**Comment by rodrigopmatias** [comment]
Sample

**Comment by rodrigopmatias** [comment]
Hi @mher,

could you give evaluated in the pull request made to flower, it offers a better view of the arguments passed to a task allowing a better understanding when solving problems.

**Comment by rodrigopmatias** [comment]
dont know why the tests failed to travis, run in the same environment who spoke on my machine and everything worked out.

**Comment by mher** [comment]
Merged, thanks!

**Comment by mher** [comment]
`pre` css needs some customization

**Comment by rodrigopmatias** [comment]
@mher 

it was not necessary any customization of css, but it was defective , send a screenshot of what I can fix .

**Pull request merged**
