### PR TITLE
Adding capability to get queue lengths via api request

### PR DESCRIPTION
**Pull request by raghuramos1987**
Feature at https://github.com/mher/flower/issues/328

### CODE REVIEW

**Comment by mher** [comment]
Thanks! Can you also add docs?

**Comment by raghuramos1987** [comment]
It looks like I used the next version of ipython notebook. If thats not desirable then I can redo the docs with the older version.

**Comment by mher** [comment]
The api docs are generated from method docstrings. For example http://flower.readthedocs.org/en/latest/api.html#post--api-task-async-apply-(.+) is generated from https://github.com/mher/flower/blob/master/flower/api/tasks.py#L158-L197

**Comment by mher** [comment]
ipython notbook is an optional format

**Comment by raghuramos1987** [comment]
oh! i see what you mean. I'll add those as part of a separate PR.

**Comment by mher** [comment]
Thanks @raghuramos1987 !

**Pull request merged**
