### PR TITLE
Added worker status filtering toolbar

### PR DESCRIPTION
**Pull request by louich**
With cloud native apps, worker are sometimes intended to have a short life and so the fact that we always see the dead workers as "offline" in the dashboard is kind of anoying. As I've seen it has been proposed (but refused)  to have the [ability to remove offline workers](https://github.com/mher/flower/issues/604) with the [PR 649](https://github.com/mher/flower/pull/649), which was determined to be too intrusive.

I propose a simple filter from radio buttons inserted into the datatable toolbar, which is blending with the current UI, easy to use and is of great use when we want to check either the "dead" or the "live" workers.

### CODE REVIEW

**Comment by dashdanw** [comment]
+1

**Comment by williammcbroom** [comment]
This is a much needed feature for users in auto-scaling worker environments. It would be very helpful if this PR could be merged in.

**Comment by davetuner** [comment]
+1

**Comment by aambrozkiewicz** [comment]
👀

**Comment by emoreth** [comment]
+1

**Comment by rafaelreuber** [comment]
+1

**Comment by jheld** [comment]
This seems like a really nice intermediate step/solution for cloud-native and the other code changes for the reset/clear of old offline workers.

They're both valid changes and this one is even less political!

@mher if the conflict is resolved, can we merge this?

**Comment by jheld** [comment]
@mher If this conflict is resolved (or a PR based on it with conflicts resolved), can this be merged?

**Comment by mher** [comment]
#852 introduces `--purge_offline_workers` option for hiding offline workers

**Pull request closed without merging**
