### PR TITLE
add back dashboard refresh button

### PR DESCRIPTION
**Pull request by adonisnafeh**
Fixes issue mentioned in #856. The refresh functionality is already there and is triggered by adding /?refresh=True to the url, I added a button that points to the current page with the refresh parameter appended to the url.

### CODE REVIEW

**Comment by jheld** [comment]
So this forces flower to re-setup its worker cache data, using the button? In this case, is your unknown worker actually online?

**Comment by adonisnafeh** [comment]
The button reloads the page with the query string refresh=True which triggers [this code](https://github.com/mher/flower/blob/master/flower/views/dashboard.py#L31)  that updates the list of the workers in the app. The button was there previously but was removed in this [commit](https://github.com/mher/flower/commit/fe4277ad14162fd0b4a97c0ee3861ba0c7ca265f#diff-daf1a06897b23423690c155ca957bcd9 ). The commit removes the button from the interface but the code that performs the update is still there. 

The workers are online and you can see its activities in all the charts except for the Queued tasks. Clicking the button refreshes the list of workers and the activity starts showing up in that chart.

**Comment by killthekitten** [comment]
Does not solve the #856 for my case

**Comment by jheld** [comment]
Thanks for the merge. But yeah seems we still will have an issue with offline workers?

**Pull request merged**
