### PR TITLE
enabling cors by adding tornado cors mixin

### PR DESCRIPTION
**Pull request by asmodehn**
simple change, just following tornado-cors doc made it work for me...
This is a cherry pick from a change that I tested on top of 0.8

Let me know if I should make more changes...

### CODE REVIEW

**Comment by johnarnold** [comment]
I tested this successfully on my integration branch, and confirmed it fixed issues with cors that were cropping up with swagger-ui.

**Comment by p1nox** [comment]
Is there a reason why this is not merged? Or there is a configuration to enable cross origin somewhere?

**Comment by liufuyang** [comment]
@mmange @mher can we still merge this or? I seem to encountered similar errors as mentioned here https://github.com/mher/flower/issues/429

**Comment by endymonium** [comment]
This merge also fixes my issues ... @mher @mmange is there a reason why this is not merged yet? Is there another solution?

**Comment by mccarthyryanc** [comment]
Trying to deal with CORS issues and would love to see this merged!

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/pull/994

**Pull request closed without merging**
