### PR TITLE
#358 Search tasks by args/kwargs

### PR DESCRIPTION
**Pull request by Melevir**

### CODE REVIEW

**Comment by mher** [comment]
Thanks for the pull request! I'd suggest a couple of improvements:

1. Use search language like github search
    `foo`  find all tasks containing foo in args, kwargs or result
    `args:foo` find all tasks containing foo in arguments
    `kwargs:foo=bar` find all tasks containing foo=bar keyword
    `result:foo` find all tasks containing foo in result

    if the search term contains spaces it should be enclosed in “ (e.g. args:”hello world”)
2. Document search behavior
3. Move Search, Received and Started controls to the second column of filter box

**Comment by Melevir** [comment]
If I missed something or you have more improvements - please, tell me. I'll be glad to fix that.

**Comment by mher** [comment]
Sorry for the late answer. It looks like there are some problems with column alignments.
untitled

We can try to narrow the space between columns and/or make Received/Started boxes smaller.

**Comment by mher** [comment]
Merged, thanks! Will fix the alignment later.

**Comment by Melevir** [comment]
Damn, totally forgot about that. Sorry, will fix that.

**Pull request merged**
