### PR TITLE
Add received and started in API list tasks

### PR DESCRIPTION
**Pull request by raimonesteve**
When working with API, received and started parameters filter tasks by dates.

Example:

``` html
http://localhost:5555/api/tasks?received-start=2015-12-28 23:00
http://localhost:5555/api/tasks?received-start=2015-12-28 23:00&received-end=2015-12-29 23:00
```

Also you could search a task by UUID (if exist or not) without call request info uri.

Example:

``` html
http://localhost:5555/api/tasks?task-id=ada92cb7-8c4e-4b29-8f63-05660ccc3ad1
```

### CODE REVIEW

**Comment by mher** [comment]
Why don't you use /task/info api method? It returns task by UUID.

**Comment by raimonesteve** [comment]
Why to do a lot of API connection to know each UUID task? For example, to do a list/view tasks (or search/read tasks).

**Comment by jheld** [comment]
What's the status of this?

**Comment by jheld** [comment]
I think this is worthwhile. I think I did something similar on my Elasticsearch PR.

Can we add a test and consider a merge @mher?

**Pull request closed without merging**
