### PR TITLE
Fixed issue that the worker detail page could not be opened

### PR DESCRIPTION
**Pull request by Ensteinjun**
The previous pull request was not standard, I re-requested one.
fixed: https://github.com/mher/flower/issues/851

### CODE REVIEW

**Comment by Ensteinjun** [comment]
https://github.com/mher/flower/issues/851

**Comment by Ensteinjun** [comment]
> possible to test the change proposed?

before the fix:
before

after fixed:
now

**Comment by pyprogrammerblog** [comment]
Hi @mher, @auvipy and @Ensteinjun could you please merge this pull request? we need in our project :)

**Comment by Jamim** [comment]
Hello @Ensteinjun,

Thank you for this PR!
Can you please resolve conflicts?

Thank you!

**Comment by Ensteinjun** [comment]
> Hello @Ensteinjun,
> 
> Thank you for this PR!
> Can you please resolve conflicts?
> 
> Thank you!

done.

**Comment by Jamim** [comment]
Hello @mher,
Can you please take a look at this PR?
It seems like these changes might fix an old issue.
Thanks!

**Comment by mher** [comment]
This pull request replaces parallel requests with sequential which is not acceptable

**Pull request closed without merging**
