### PR TITLE
Fix "not JSON serializable" `TypeError` for /api/task/info

### PR DESCRIPTION
**Pull request by bosonogi**
Related to #617

### CODE REVIEW

**Comment by johnarnold** [comment]
Confirmed fix!  Thanks @bosonogi

**Comment by mher** [comment]
Merged, thanks!

**Comment by mher** [comment]
Please add your name to the list of contributors

**Comment by bosonogi** [comment]
Thanks @mher 
As you already merged this, I've added my name to CONTRIBUTORS in #724 
In case that PR will not get merged, please cherry-pick 8f78de8 into the master branch.

**Comment by mher** [comment]
@bdrung this PR broke dashboard tests.

**Comment by bdrung** [comment]
@mher, did you mean me or @bosonogi?

**Comment by mher** [comment]
Yep, sorry @bdrung

**Comment by bosonogi** [comment]
@mher It's not this PR that broke the dashboard tests, they passed before it was merged.

The `test_unknown_worker` began failing with Celery 4.1 and I've tracked down the problem to this point:

https://github.com/mher/flower/blob/d2d24893a30dafc1b840376b2aef7acdb94bd3d2/flower/api/control.py#L37

Calls to `inspect` methods for an unknown worker block forever. I didn't manage to figure out why this is happening and what would be the best thing for Flower to do about it. Any ideas?

**Comment by ocervell** [comment]
This is still breaking in 0.9.2:

```
   ERROR -- Uncaught exception GET /api/task/info/9eb1e817-6657-4f9f-a816-25f65dd373b3 (::1)
HTTPServerRequest(protocol='http', host='localhost:5555', method='GET', uri='/api/task/info/9eb1e817-6657-4f9f-a816-25f65dd373b3', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8,fr-FR;q=0.6,fr;q=0.4,da;q=0.2', 'Accept-Encoding': 'gzip, deflate, br', 'Host': 'localhost:5555', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'sessionid=dzgtpa3vut2wr6uca78tpco4mmly66m9; csrftoken=k3XoucqgCedJtH0Qv4i9Qe87UPmSeXwC; __utma=111872281.1561610844.1500738949.1500738949.1500738949.1; __utmc=111872281; __utmz=111872281.1500738949.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); session=927d33f567d59a01_5a1dd363.kv-N1Rt5VPSZ8Jz_Was98iCayFw', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/Users/ocervell/.virtualenvs/ndc/lib/python2.7/site-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/ocervell/.virtualenvs/ndc/lib/python2.7/site-packages/tornado/web.py", line 2897, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/ocervell/.virtualenvs/ndc/lib/python2.7/site-packages/flower/api/tasks.py", line 604, in get
    self.write(response)
  File "/Users/ocervell/.virtualenvs/ndc/lib/python2.7/site-packages/tornado/web.py", line 715, in write
    chunk = escape.json_encode(chunk)
  File "/Users/ocervell/.virtualenvs/ndc/lib/python2.7/site-packages/tornado/escape.py", line 82, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <_weakrefset.WeakSet object at 0x112d3e590> is not JSON serializable
```

**Comment by bosonogi** [comment]
@ocervell The 0.9.2 release was tagged on Jun 18, before this fix was merged.

**Comment by ocervell** [comment]
@bosonogi Thanks, I will pull the last master. Any chance to see it in a `pip` release soon ?

**Comment by bosonogi** [comment]
@ocervell Sorry, not up to me -- I just made this PR.
@mher Any comment on the timeline of the next release?

**Comment by sergiofblopes** [comment]
Is there any news regarding a new pip release? I have been searching but with no luck.
Thanks in advance!

**Comment by rvaidya** [comment]
I too would like to see this fixed in pip

**Comment by MoezGholami** [comment]
It seems this very pull request is included in 0.9.3 but the [docker image is not re-released yet](https://hub.docker.com/r/mher/flower/tags). I'm facing #617 in my production environment (fixed by having my own docker image) and it would be good if we get the latest version in the canonical docker image too.

**Pull request merged**
